//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracker.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Projects = new HashSet<Project>();
            this.Schools = new HashSet<School>();
            this.Attachments = new HashSet<Attachment>();
            this.Edits = new HashSet<ProjectEdit>();
            this.VotedProjects = new HashSet<Project>();
        }
    
        [Required,
         Display(Name="Employee ID")]
        public int Emp_Id { get; set; }

        [Required,
         StringLength(32, ErrorMessage = Helpers.TOO_LONG)]
        public string Username { get; set; }

        [Required,
         StringLength(32, ErrorMessage = Helpers.TOO_LONG)]
        public string Password { get; set; }
        
        [Required,
         Display(Name = "First Name"),
         StringLength(32, ErrorMessage = Helpers.TOO_LONG)]
        public string FName { get; set; }
        
        [Display(Name = "Last Name"),
         StringLength(32, ErrorMessage = Helpers.TOO_LONG)]
        public string LName { get; set; }

        [Display(Name = "Full Name")]
        public string FullName
        {
            get { return FName + " " + LName; }
        }

        [Required,
         Display(Name = "Role ID")]
        public int Role_Id { get; set; }
    
        // Navigation properties
        public virtual Role Role { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<School> Schools { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<ProjectEdit> Edits { get; set; }
        public virtual ICollection<Project> VotedProjects { get; set; }

        [Display(Name = "Votes")]
        public int VoteCount
        {
            get { return VotedProjects.Count; }
        }

        public bool CanEdit(Project project)
        {
            if (Role.Is(Role.Enum.Admin) || Emp_Id == project.Author_Id)
                return true;
            foreach (School s in Schools)
            {
                if (s.School_Id == project.School_Id)
                    return true;
            }
            return false;
        }
    }
}
