//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Linq;
    
    public partial class Project
    {
        public Project()
        {
            this.Attachments = new HashSet<Attachment>();
            this.Edits = new HashSet<ProjectEdit>();
            this.Voters = new HashSet<Employee>();
        }

        #region DB ATTRIBUTES

        [Required,
         Display(Name = "Project ID")]
        public int Project_Id { get; set; }
        
        [Required,
         Display(Prompt = "Give the project a clever name"),
         StringLength(32, ErrorMessage = Helpers.TOO_LONG)]
        public string Title { get; set; }

        [Required,
         Display(Name = "Quick Pitch",
                 Prompt = "Summarize the project in a sentence or two"),
         DataType(DataType.MultilineText),
         StringLength(150, ErrorMessage = Helpers.TOO_LONG)]
        public string Short_Description { get; set; }

        [Required,
         Display(Prompt = "Give a detailed explanation"),
         DataType(DataType.MultilineText),
         StringLength(500, ErrorMessage = Helpers.TOO_LONG)]
        public string Description { get; set; }

        [Required,
         Display(Prompt = "How will this benefit Commerce?"),
         DataType(DataType.MultilineText),
         StringLength(250, ErrorMessage = Helpers.TOO_LONG)]
        public string Justification { get; set; }

        [Display(Prompt = "Give notes on progress"),
         DataType(DataType.MultilineText),
         StringLength(500, ErrorMessage = Helpers.TOO_LONG)]
        public string Notes { get; set; }

        [Required,
         Display(Name="Status ID")]
        public int Status_Id { get; set; }
        
        [Required,
         Display(Name = "School ID")]
        public int School_Id { get; set; }
        
        [Required,
         Display(Name = "Author ID")]
        public int Author_Id { get; set; }

        [Required,
         Display(Name="Created")]
        public DateTime Submit_Date { get; set; }

        #endregion // DB ATTRIBUTES

        #region NAVIGATION PROPERTIES

        public virtual Status Status { get; set; }
        public virtual School School { get; set; }
        public virtual Employee Author { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<ProjectEdit> Edits { get; set; }
        public virtual ICollection<Employee> Voters { get; set; }

        #endregion // NAVIGATION PROPERTIES

        #region CUSTOM

        [Display(Name="Last Edited")]
        public ProjectEdit LastEdit
        {
            get { return Edits.FirstOrDefault(e => (e.Edit_Id == Edits.Max(lastEdit => lastEdit.Edit_Id))); }
        }

        [Display(Name = "Votes")]
        public int VoteCount
        {
            get { return Voters.Count; }
        }

        public void DeleteDependents(System.Web.HttpServerUtilityBase server, ProjectTrackerEntities db)
        {
            db.Attachments.RemoveRange(Attachments);
            db.ProjectEdits.RemoveRange(Edits);
            Voters = null;
            db.SaveChanges();
            string dirPath = server.MapPath("~/App_Data/Attachments/" + Project_Id);
            DirectoryInfo dir = new DirectoryInfo(dirPath);
            if (dir.Exists)
                dir.Delete(true);
        }

        #endregion // CUSTOM
    }
}
